# -*- generated by 1.0.9 -*-
import da
PatternExpr_271 = da.pat.ConstantPattern('Shutdown')
PatternExpr_275 = da.pat.BoundPattern('_BoundPattern276_')
PatternExpr_289 = da.pat.ConstantPattern('Shutdown')
PatternExpr_293 = da.pat.FreePattern('olympus')
PatternExpr_305 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('olympus_'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_'), da.pat.FreePattern('tail_'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_355 = da.pat.TuplePattern([da.pat.ConstantPattern('Key'), da.pat.FreePattern('private_key_')])
PatternExpr_377 = da.pat.TuplePattern([da.pat.ConstantPattern('Request'), da.pat.FreePattern('type'), da.pat.FreePattern('request_from'), da.pat.FreePattern('client'), da.pat.FreePattern('request_id'), da.pat.FreePattern('args')])
PatternExpr_634 = da.pat.TuplePattern([da.pat.ConstantPattern('Result_shuttle'), da.pat.FreePattern('request_from'), da.pat.FreePattern('request_id'), da.pat.FreePattern('result_shuttle')])
PatternExpr_277 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern283_')]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_1061 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.FreePattern('sender')])
PatternExpr_1078 = da.pat.TuplePattern([da.pat.ConstantPattern('Get_configuration'), da.pat.FreePattern('client'), da.pat.FreePattern('client_name')])
PatternExpr_1110 = da.pat.TuplePattern([da.pat.ConstantPattern('Reconfiguration'), da.pat.FreePattern('sender'), da.pat.FreePattern('proof_of_misbehavior')])
PatternExpr_1165 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])
PatternExpr_1188 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1172 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])])
PatternExpr_1192 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_1238 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_')])
PatternExpr_1247 = da.pat.FreePattern('olympus')
PatternExpr_1268 = da.pat.TuplePattern([da.pat.ConstantPattern('Keys'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_1275 = da.pat.FreePattern('olympus')
PatternExpr_1301 = da.pat.TuplePattern([da.pat.ConstantPattern('Operation_result'), da.pat.FreePattern('result_shuttle')])
PatternExpr_1351 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1354_'), da.pat.BoundPattern('_BoundPattern1355_')])
PatternExpr_1408 = da.pat.BoundPattern('_BoundPattern1414_')
PatternExpr_1447 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1358 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1368_'), da.pat.BoundPattern('_BoundPattern1369_')])])
PatternExpr_1416 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern1423_')])
PatternExpr_1451 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
_config_object = {'channel': {'reliable', 'fifo'}}
from nacl.hash import sha256
from nacl.encoding import HexEncoder
from nacl.signing import SigningKey, VerifyKey
client_running_state = dict()

class Replica(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ReplicaReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_0', PatternExpr_271, sources=[PatternExpr_275], destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_1', PatternExpr_289, sources=[PatternExpr_293], destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_288]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_2', PatternExpr_305, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_304]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_3', PatternExpr_355, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_354]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_4', PatternExpr_377, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_376]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_5', PatternExpr_634, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_633])])

    def setup(self, id, name, **rest_1742):
        super().setup(id=id, name=name, **rest_1742)
        self._state.id = id
        self._state.name = name
        self._state.status = 0
        self._state.running_state = dict()
        self._state.order_proof = list()
        self._state.result_proof = list()
        self._state.result_cache = dict()
        self._state.slot_number = 0
        self._state.olympus = None
        self._state.replicas = None
        self._state.head = None
        self._state.tail = None
        self._state.replica_public_keys = None
        self._state.private_key = None

    def run(self):
        self._state.status = 1
        super()._label('_st_label_268', block=False)
        _st_label_268 = 0
        while (_st_label_268 == 0):
            _st_label_268 += 1
            if PatternExpr_277.match_iter(self._ReplicaReceivedEvent_0, _BoundPattern283_=self._state.olympus, SELF_ID=self._id):
                _st_label_268 += 1
            else:
                super()._label('_st_label_268', block=True)
                _st_label_268 -= 1

    def update_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                self._state.running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in self._state.running_state):
                    return self._state.running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in self._state.running_state) and (args[1] <= len(self._state.running_state[args[0]]))):
                    self._state.running_state[args[0]] = self._state.running_state[args[0]][int(args[1]):]
                    return self._state.running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in self._state.running_state):
                    self._state.running_state[args[0]] = (self._state.running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def validate_shuttle(self, slot_number, operation, shuttle):
        (self._state.order_proof, self._state.result_proof) = shuttle
        for i in self._state.order_proof:
            if ((i[0] == slot_number) and (not (i[1] == operation))):
                return False
        hash = self._state.result_proof[0][1]
        for i in self._state.result_proof:
            if ((not (i[0] == operation)) or (not (i[1] == hash))):
                return False
        return True

    def validate_result_shuttle(self, result_shuttle):
        (result, self._state.result_proof) = result_shuttle
        hash = self.calculate_hash(result)
        for i in self._state.result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def send_(self, data, to_):
        self.send(data, to=to_)

    def _Replica_handler_288(self, olympus):
        self._state.status = 2
        self.output((self._state.name + ' is immutable and shutting down.'))
    _Replica_handler_288._labels = None
    _Replica_handler_288._notlabels = None

    def _Replica_handler_304(self, olympus_, replicas_, head_, tail_, replica_public_keys_):
        self._state.olympus = olympus_
        self._state.replicas = replicas_
        self._state.head = head_
        self._state.tail = tail_
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_304._labels = None
    _Replica_handler_304._notlabels = None

    def _Replica_handler_354(self, private_key_):
        self._state.private_key = private_key_
        self.output((self._state.name + ' have received its private key from Olympus.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_354._labels = None
    _Replica_handler_354._notlabels = None

    def _Replica_handler_376(self, type, request_from, client, request_id, args):
        self.output((((((str(type) + ' request with request id ') + str(request_id)) + ' received by ') + self._state.name) + '.'))
        if (request_from == client):
            if (request_id in self._state.result_cache):
                self.send_(('Operation_result', self._state.result_cache[request_id]), client)
                self.output((('Result sent from cache of ' + self._state.name) + '.'))
                return
            elif (not (self._id == self._state.head)):
                self.send_(('Request', type, self._id, client, request_id, args), self._state.head)
                return
        if (self._id == self._state.head):
            result = self.update_running_state(type, args)
            self._state.slot_number += 1
            self._state.order_proof.append([self._state.slot_number, (type, args), self._state.id])
            self._state.result_proof = list()
            self._state.result_proof.append([(type, args), self.calculate_hash(result)])
            shuttle = (self._state.order_proof, self._state.result_proof)
            self.send_(('Request', type, self._id, client, request_id, [self._state.slot_number, (type, args), shuttle]), self._state.replicas[(self._state.id + 1)])
        else:
            (self._state.slot_number, operation, shuttle) = args
            if self.validate_shuttle(self._state.slot_number, operation, shuttle):
                (type, operation_args) = operation
                (self._state.order_proof, self._state.result_proof) = shuttle
                result = self.update_running_state(type, operation_args)
                self._state.order_proof.append([self._state.slot_number, (type, operation_args), self._state.id])
                self._state.result_proof.append([(type, operation_args), self.calculate_hash(result)])
                shuttle = (self._state.order_proof, self._state.result_proof)
                if (self._id == self._state.tail):
                    result_shuttle = [result, self._state.result_proof]
                    self.send_(('Operation_result', result_shuttle), client)
                    self.send_(('Operation_result_' + str(request_id)), client)
                    self.send_(('Result_shuttle', self._id, request_id, result_shuttle), self._state.tail)
                else:
                    self.send_(('Request', type, self._id, client, request_id, [self._state.slot_number, (type, operation_args), shuttle]), self._state.replicas[(self._state.id + 1)])
            else:
                self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
    _Replica_handler_376._labels = None
    _Replica_handler_376._notlabels = None

    def _Replica_handler_633(self, request_from, request_id, result_shuttle):
        if self.validate_result_shuttle(result_shuttle):
            self._state.result_cache[request_id] = result_shuttle
            if (not (self._id == self._state.head)):
                self.send_(('Result_shuttle', self._id, request_id, result_shuttle), self._state.replicas[(self._state.id - 1)])
            self.output((('Result shuttle is at ' + self._state.name) + '.'))
    _Replica_handler_633._labels = None
    _Replica_handler_633._notlabels = None

class Olympus(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._OlympusReceivedEvent_3 = []
        self._OlympusReceivedEvent_4 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_0', PatternExpr_1061, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1060]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_1', PatternExpr_1078, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1077]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_2', PatternExpr_1110, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1109]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_3', PatternExpr_1165, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_4', PatternExpr_1188, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, name, num_replicas, **rest_1742):
        super().setup(name=name, num_replicas=num_replicas, **rest_1742)
        self._state.name = name
        self._state.num_replicas = num_replicas
        self._state.replicas = list()
        self._state.replica_private_keys = list()
        self._state.replica_public_keys = list()
        self._state.head = None
        self._state.tail = None
        for i in range(self._state.num_replicas):
            if (i == 0):
                replica = self.new(Replica, args=(i, 'Head'))
                self._state.head = replica
            elif (i == (self._state.num_replicas - 1)):
                replica = self.new(Replica, args=(i, 'Tail'))
                self._state.tail = replica
            else:
                replica = self.new(Replica, args=(i, ('Replica ' + str(i))))
            self._state.replicas.append(replica)
            signing_key = SigningKey.generate()
            verify_key = signing_key.verify_key.encode(encoder=HexEncoder)
            self._state.replica_private_keys.append(signing_key)
            self._state.replica_public_keys.append(verify_key)

    def run(self):
        self._start(self._state.replicas)
        self.send(('Configuration', self._id, self._state.replicas, self._state.head, self._state.tail, self._state.replica_public_keys), to=self._state.replicas)
        for i in range(len(self._state.replicas)):
            self.send(('Key', self._state.replica_private_keys[i]), to=self._state.replicas[i])
        super()._label('_st_label_1162', block=False)
        _st_label_1162 = 0
        while (_st_label_1162 == 0):
            _st_label_1162 += 1
            if PatternExpr_1172.match_iter(self._OlympusReceivedEvent_3, SELF_ID=self._id):
                _st_label_1162 += 1
            else:
                super()._label('_st_label_1162', block=True)
                _st_label_1162 -= 1
        super()._label('_st_label_1185', block=False)
        _st_label_1185 = 0
        while (_st_label_1185 == 0):
            _st_label_1185 += 1
            if PatternExpr_1192.match_iter(self._OlympusReceivedEvent_4, SELF_ID=self._id):
                _st_label_1185 += 1
            else:
                super()._label('_st_label_1185', block=True)
                _st_label_1185 -= 1

    def _Olympus_handler_1060(self, sender):
        self.output((('ACK from ' + str(sender)) + '.'))
    _Olympus_handler_1060._labels = None
    _Olympus_handler_1060._notlabels = None

    def _Olympus_handler_1077(self, client, client_name):
        self.send(('Configuration', self._state.replicas, self._state.head), to=client)
        self.send(('Keys', self._state.replica_public_keys), to=client)
        self.output((('Configuration sent to ' + str(client_name)) + '.'))
    _Olympus_handler_1077._labels = None
    _Olympus_handler_1077._notlabels = None

    def _Olympus_handler_1109(self, sender, proof_of_misbehavior):
        self.output((('Reconfiguration request received from ' + str(sender)) + '.'))
        self.output('No reconfiguration mechanism implemented yet.')
    _Olympus_handler_1109._labels = None
    _Olympus_handler_1109._notlabels = None

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ClientReceivedEvent_3 = []
        self._ClientReceivedEvent_4 = []
        self._ClientReceivedEvent_5 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_1238, sources=[PatternExpr_1247], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1237]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_1', PatternExpr_1268, sources=[PatternExpr_1275], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1267]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_2', PatternExpr_1301, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1300]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_3', PatternExpr_1351, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_4', PatternExpr_1408, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_5', PatternExpr_1447, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, name, olympus, request_id, time_out, operations, **rest_1742):
        super().setup(name=name, olympus=olympus, request_id=request_id, time_out=time_out, operations=operations, **rest_1742)
        self._state.name = name
        self._state.olympus = olympus
        self._state.request_id = request_id
        self._state.time_out = time_out
        self._state.operations = operations
        self._state.replicas = None
        self._state.head = None
        self._state.replica_public_keys = None

    def run(self):
        if (self._state.replicas is None):
            self.send(('Get_configuration', self._id, self._state.name), to=self._state.olympus)
            super()._label('_st_label_1348', block=False)
            _st_label_1348 = 0
            while (_st_label_1348 == 0):
                _st_label_1348 += 1
                if PatternExpr_1358.match_iter(self._ClientReceivedEvent_3, _BoundPattern1368_=self._state.replicas, _BoundPattern1369_=self._state.head, SELF_ID=self._id):
                    _st_label_1348 += 1
                else:
                    super()._label('_st_label_1348', block=True)
                    _st_label_1348 -= 1
        for op in self._state.operations:
            self.output((('Local client state is updated with response ' + self.update_client_running_state(op[0], op[1])) + '.'))
            retry = 0
            while True:
                self.send_request(op[0], op[1], retry)
                super()._label('_st_label_1405', block=False)
                _st_label_1405 = 0
                self._timer_start()
                while (_st_label_1405 == 0):
                    _st_label_1405 += 1
                    if PatternExpr_1416.match_iter(self._ClientReceivedEvent_4, _BoundPattern1423_=('Operation_result_' + str(self._state.request_id)), SELF_ID=self._id):
                        break
                        _st_label_1405 += 1
                    elif self._timer_expired:
                        self.output('Timeout: Retrying.')
                        retry = 1
                        _st_label_1405 += 1
                    else:
                        super()._label('_st_label_1405', block=True, timeout=self._state.time_out)
                        _st_label_1405 -= 1
                else:
                    if (_st_label_1405 != 2):
                        continue
                if (_st_label_1405 != 2):
                    break
        self.output((('Local running state of client after the given set of operations: ' + str(client_running_state)) + '.'))
        super()._label('_st_label_1444', block=False)
        _st_label_1444 = 0
        while (_st_label_1444 == 0):
            _st_label_1444 += 1
            if PatternExpr_1451.match_iter(self._ClientReceivedEvent_5, SELF_ID=self._id):
                _st_label_1444 += 1
            else:
                super()._label('_st_label_1444', block=True)
                _st_label_1444 -= 1

    def update_client_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                client_running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in client_running_state):
                    return client_running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in client_running_state) and (args[1] <= len(client_running_state[args[0]]))):
                    client_running_state[args[0]] = client_running_state[args[0]][int(args[1]):]
                    return client_running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in client_running_state):
                    client_running_state[args[0]] = (client_running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def send_request(self, type, args, retry):
        if retry:
            self.send(('Request', type, self._id, self._id, self._state.request_id, args), to=self._state.head)
        else:
            self._state.request_id += 1
            self.send(('Request', type, self._id, self._id, self._state.request_id, args), to=self._state.head)

    def validate_result(self, result, result_proof):
        hash = self.calculate_hash(result)
        for i in result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def _Client_handler_1237(self, replicas_, head_, olympus):
        self._state.replicas = replicas_
        self._state.head = head_
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1237._labels = None
    _Client_handler_1237._notlabels = None

    def _Client_handler_1267(self, replica_public_keys_, olympus):
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' received the public keys of replicas from Olympus.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1267._labels = None
    _Client_handler_1267._notlabels = None

    def _Client_handler_1300(self, result_shuttle):
        (result, result_proof) = result_shuttle
        if self.validate_result(result, result_proof):
            self.output((((result + ' received by ') + self._state.name) + '.'))
        else:
            self.send(('Reconfiguration', self._state.name, result_shuttle), to=self._state.olympus)
    _Client_handler_1300._labels = None
    _Client_handler_1300._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        (num_replicas, request_id_counter, time_out) = (3, 0, 10)
        olympus = self.new(Olympus, args=('Olympus', num_replicas))
        self._start(olympus)
        operations = [('put', ['name', 'ankit']), ('get', ['name']), ('append', ['name', 'aggarwal']), ('get', ['name']), ('slice', ['name', 5]), ('get', ['name'])]
        client = self.new(Client, args=('Client', olympus, request_id_counter, time_out, operations))
        self._start(client)
