# -*- generated by 1.0.9 -*-
import da
PatternExpr_277 = da.pat.ConstantPattern('Shutdown')
PatternExpr_281 = da.pat.BoundPattern('_BoundPattern282_')
PatternExpr_295 = da.pat.ConstantPattern('Shutdown')
PatternExpr_299 = da.pat.FreePattern('olympus')
PatternExpr_311 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('olympus_'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_'), da.pat.FreePattern('tail_'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_361 = da.pat.TuplePattern([da.pat.ConstantPattern('Key'), da.pat.FreePattern('private_key_')])
PatternExpr_383 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Request'), da.pat.FreePattern('type'), da.pat.FreePattern('request_from'), da.pat.FreePattern('client'), da.pat.FreePattern('request_id'), da.pat.FreePattern('args')])
PatternExpr_693 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Result_shuttle'), da.pat.FreePattern('request_from'), da.pat.FreePattern('request_id'), da.pat.FreePattern('result_shuttle')])
PatternExpr_283 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern289_')]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_1188 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.FreePattern('sender')])
PatternExpr_1205 = da.pat.TuplePattern([da.pat.ConstantPattern('Get_configuration'), da.pat.FreePattern('client'), da.pat.FreePattern('client_name')])
PatternExpr_1237 = da.pat.TuplePattern([da.pat.ConstantPattern('Reconfiguration'), da.pat.FreePattern('sender'), da.pat.FreePattern('proof_of_misbehavior')])
PatternExpr_1292 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])
PatternExpr_1315 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1299 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])])
PatternExpr_1319 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_1365 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_')])
PatternExpr_1374 = da.pat.FreePattern('olympus')
PatternExpr_1395 = da.pat.TuplePattern([da.pat.ConstantPattern('Keys'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_1402 = da.pat.FreePattern('olympus')
PatternExpr_1428 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Operation_result'), da.pat.FreePattern('result_shuttle')])
PatternExpr_1506 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1509_'), da.pat.BoundPattern('_BoundPattern1510_')])
PatternExpr_1563 = da.pat.BoundPattern('_BoundPattern1569_')
PatternExpr_1602 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1513 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1523_'), da.pat.BoundPattern('_BoundPattern1524_')])])
PatternExpr_1571 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern1578_')])
PatternExpr_1606 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
_config_object = {'channel': {'reliable', 'fifo'}}
from nacl.hash import sha256
from nacl.encoding import HexEncoder
from nacl.signing import SigningKey, VerifyKey
from nacl.exceptions import BadSignatureError
from ast import literal_eval
client_running_state = dict()

class Replica(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ReplicaReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_0', PatternExpr_277, sources=[PatternExpr_281], destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_1', PatternExpr_295, sources=[PatternExpr_299], destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_294]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_2', PatternExpr_311, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_310]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_3', PatternExpr_361, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_360]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_4', PatternExpr_383, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_382]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_5', PatternExpr_693, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_692])])

    def setup(self, id, name, **rest_1899):
        super().setup(id=id, name=name, **rest_1899)
        self._state.id = id
        self._state.name = name
        self._state.status = 0
        self._state.running_state = dict()
        self._state.order_proof = list()
        self._state.result_proof = list()
        self._state.result_cache = dict()
        self._state.slot_number = 0
        self._state.olympus = None
        self._state.replicas = None
        self._state.head = None
        self._state.tail = None
        self._state.replica_public_keys = None
        self._state.private_key = None

    def run(self):
        self._state.status = 1
        super()._label('_st_label_274', block=False)
        _st_label_274 = 0
        while (_st_label_274 == 0):
            _st_label_274 += 1
            if PatternExpr_283.match_iter(self._ReplicaReceivedEvent_0, _BoundPattern289_=self._state.olympus, SELF_ID=self._id):
                _st_label_274 += 1
            else:
                super()._label('_st_label_274', block=True)
                _st_label_274 -= 1

    def update_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                self._state.running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in self._state.running_state):
                    return self._state.running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in self._state.running_state) and (args[1] <= len(self._state.running_state[args[0]]))):
                    self._state.running_state[args[0]] = self._state.running_state[args[0]][int(args[1]):]
                    return self._state.running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in self._state.running_state):
                    self._state.running_state[args[0]] = (self._state.running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def validate_shuttle(self, slot_number, operation, shuttle):
        (self._state.order_proof, self._state.result_proof) = shuttle
        for i in self._state.order_proof:
            if ((i[0] == slot_number) and (not (i[1] == operation))):
                return False
        hash = self._state.result_proof[0][1]
        for i in self._state.result_proof:
            if ((not (i[0] == operation)) or (not (i[1] == hash))):
                return False
        return True

    def validate_result_shuttle(self, result_shuttle):
        (result, self._state.result_proof) = result_shuttle
        hash = self.calculate_hash(result)
        for i in self._state.result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def send_(self, data, to_):
        data = ([self._state.id] + list(data))
        data[(- 1)] = self._state.private_key.sign(str(data[(- 1)]).encode('utf-8'))
        self.send(tuple(data), to=to_)

    def _Replica_handler_294(self, olympus):
        self._state.status = 2
        self.output((self._state.name + ' is immutable and shutting down.'))
    _Replica_handler_294._labels = None
    _Replica_handler_294._notlabels = None

    def _Replica_handler_310(self, olympus_, replicas_, head_, tail_, replica_public_keys_):
        self._state.olympus = olympus_
        self._state.replicas = replicas_
        self._state.head = head_
        self._state.tail = tail_
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_310._labels = None
    _Replica_handler_310._notlabels = None

    def _Replica_handler_360(self, private_key_):
        self._state.private_key = private_key_
        self.output((self._state.name + ' have received its private key from Olympus.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_360._labels = None
    _Replica_handler_360._notlabels = None

    def _Replica_handler_382(self, sender_id, type, request_from, client, request_id, args):
        self.output((((((str(type) + ' request with request id ') + str(request_id)) + ' received by ') + self._state.name) + '.'))
        if (self._state.status == 0):
            self.output((self._state.name + ' is in PENDING state.'))
        elif (self._state.status == 1):
            self.output((self._state.name + ' is in ACTIVE state.'))
        elif (self._state.status == 2):
            self.output((self._state.name + ' is in IMMUTABLE state.'))
        if (self._state.status == 1):
            if (request_from == client):
                if (request_id in self._state.result_cache):
                    self.send_(('Operation_result', self._state.result_cache[request_id]), client)
                    self.output((('Result sent from cache of ' + self._state.name) + '.'))
                    return
                elif (not (self._id == self._state.head)):
                    self.send_(('Request', type, self._id, client, request_id, args), self._state.head)
                    return
            else:
                try:
                    self._state.replica_public_keys[sender_id].verify(args)
                    args = literal_eval(args.message.decode('utf-8'))
                except BadSignatureError:
                    self.output((('Verification of message sent by Replica ' + sender_id) + ' has failed.'))
                    return
            if (self._id == self._state.head):
                result = self.update_running_state(type, args)
                self._state.slot_number += 1
                self._state.order_proof.append([self._state.slot_number, (type, args)])
                self._state.result_proof = list()
                self._state.result_proof.append([(type, args), self.calculate_hash(result)])
                shuttle = (self._state.order_proof, self._state.result_proof)
                self.send_(('Request', type, self._id, client, request_id, [self._state.slot_number, (type, args), shuttle]), self._state.replicas[(self._state.id + 1)])
            else:
                (self._state.slot_number, operation, shuttle) = args
                if self.validate_shuttle(self._state.slot_number, operation, shuttle):
                    (type, operation_args) = operation
                    (self._state.order_proof, self._state.result_proof) = shuttle
                    result = self.update_running_state(type, operation_args)
                    self._state.order_proof.append([self._state.slot_number, (type, operation_args)])
                    self._state.result_proof.append([(type, operation_args), self.calculate_hash(result)])
                    shuttle = (self._state.order_proof, self._state.result_proof)
                    if (self._id == self._state.tail):
                        result_shuttle = [result, self._state.result_proof]
                        self.send_(('Operation_result', result_shuttle), client)
                        self.send(('Operation_result_' + str(request_id)), to=client)
                        self.send_(('Result_shuttle', self._id, request_id, result_shuttle), self._state.tail)
                    else:
                        self.send_(('Request', type, self._id, client, request_id, [self._state.slot_number, (type, operation_args), shuttle]), self._state.replicas[(self._state.id + 1)])
                else:
                    self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
    _Replica_handler_382._labels = None
    _Replica_handler_382._notlabels = None

    def _Replica_handler_692(self, sender_id, request_from, request_id, result_shuttle):
        try:
            self._state.replica_public_keys[sender_id].verify(result_shuttle)
            result_shuttle = literal_eval(result_shuttle.message.decode('utf-8'))
        except BadSignatureError:
            self.output((('Verification of message sent by Replica ' + sender_id) + ' has failed.'))
            return
        if self.validate_result_shuttle(result_shuttle):
            self._state.result_cache[request_id] = result_shuttle
            if (not (self._id == self._state.head)):
                self.send_(('Result_shuttle', self._id, request_id, result_shuttle), self._state.replicas[(self._state.id - 1)])
            self.output((('Result shuttle is at ' + self._state.name) + '.'))
        else:
            self.output((('Result shuttle sent by Replica ' + sender_id) + ' is not valid.'))
            self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
    _Replica_handler_692._labels = None
    _Replica_handler_692._notlabels = None

class Olympus(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._OlympusReceivedEvent_3 = []
        self._OlympusReceivedEvent_4 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_0', PatternExpr_1188, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1187]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_1', PatternExpr_1205, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1204]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_2', PatternExpr_1237, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1236]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_3', PatternExpr_1292, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_4', PatternExpr_1315, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, name, num_replicas, **rest_1899):
        super().setup(name=name, num_replicas=num_replicas, **rest_1899)
        self._state.name = name
        self._state.num_replicas = num_replicas
        self._state.replicas = list()
        self._state.replica_private_keys = list()
        self._state.replica_public_keys = list()
        self._state.head = None
        self._state.tail = None
        for i in range(self._state.num_replicas):
            if (i == 0):
                replica = self.new(Replica, args=(i, 'Head'))
                self._state.head = replica
            elif (i == (self._state.num_replicas - 1)):
                replica = self.new(Replica, args=(i, 'Tail'))
                self._state.tail = replica
            else:
                replica = self.new(Replica, args=(i, ('Replica ' + str(i))))
            self._state.replicas.append(replica)
            signing_key = SigningKey.generate()
            verify_key = signing_key.verify_key.encode(encoder=HexEncoder)
            self._state.replica_private_keys.append(signing_key)
            self._state.replica_public_keys.append(verify_key)

    def run(self):
        self._start(self._state.replicas)
        self.send(('Configuration', self._id, self._state.replicas, self._state.head, self._state.tail, self._state.replica_public_keys), to=self._state.replicas)
        for i in range(len(self._state.replicas)):
            self.send(('Key', self._state.replica_private_keys[i]), to=self._state.replicas[i])
        super()._label('_st_label_1289', block=False)
        _st_label_1289 = 0
        while (_st_label_1289 == 0):
            _st_label_1289 += 1
            if PatternExpr_1299.match_iter(self._OlympusReceivedEvent_3, SELF_ID=self._id):
                _st_label_1289 += 1
            else:
                super()._label('_st_label_1289', block=True)
                _st_label_1289 -= 1
        super()._label('_st_label_1312', block=False)
        _st_label_1312 = 0
        while (_st_label_1312 == 0):
            _st_label_1312 += 1
            if PatternExpr_1319.match_iter(self._OlympusReceivedEvent_4, SELF_ID=self._id):
                _st_label_1312 += 1
            else:
                super()._label('_st_label_1312', block=True)
                _st_label_1312 -= 1

    def _Olympus_handler_1187(self, sender):
        self.output((('ACK from ' + str(sender)) + '.'))
    _Olympus_handler_1187._labels = None
    _Olympus_handler_1187._notlabels = None

    def _Olympus_handler_1204(self, client, client_name):
        self.send(('Configuration', self._state.replicas, self._state.head), to=client)
        self.send(('Keys', self._state.replica_public_keys), to=client)
        self.output((('Configuration sent to ' + str(client_name)) + '.'))
    _Olympus_handler_1204._labels = None
    _Olympus_handler_1204._notlabels = None

    def _Olympus_handler_1236(self, sender, proof_of_misbehavior):
        self.output((('Reconfiguration request received from ' + str(sender)) + '.'))
        self.output('No reconfiguration mechanism implemented yet.')
    _Olympus_handler_1236._labels = None
    _Olympus_handler_1236._notlabels = None

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ClientReceivedEvent_3 = []
        self._ClientReceivedEvent_4 = []
        self._ClientReceivedEvent_5 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_1365, sources=[PatternExpr_1374], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1364]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_1', PatternExpr_1395, sources=[PatternExpr_1402], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1394]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_2', PatternExpr_1428, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1427]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_3', PatternExpr_1506, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_4', PatternExpr_1563, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_5', PatternExpr_1602, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, name, olympus, request_id, time_out, operations, **rest_1899):
        super().setup(name=name, olympus=olympus, request_id=request_id, time_out=time_out, operations=operations, **rest_1899)
        self._state.name = name
        self._state.olympus = olympus
        self._state.request_id = request_id
        self._state.time_out = time_out
        self._state.operations = operations
        self._state.replicas = None
        self._state.head = None
        self._state.replica_public_keys = None

    def run(self):
        if (self._state.replicas is None):
            self.send(('Get_configuration', self._id, self._state.name), to=self._state.olympus)
            super()._label('_st_label_1503', block=False)
            _st_label_1503 = 0
            while (_st_label_1503 == 0):
                _st_label_1503 += 1
                if PatternExpr_1513.match_iter(self._ClientReceivedEvent_3, _BoundPattern1523_=self._state.replicas, _BoundPattern1524_=self._state.head, SELF_ID=self._id):
                    _st_label_1503 += 1
                else:
                    super()._label('_st_label_1503', block=True)
                    _st_label_1503 -= 1
        for op in self._state.operations:
            self.output((('Local client state is updated with response ' + self.update_client_running_state(op[0], op[1])) + '.'))
            retry = 0
            while True:
                self.send_request(op[0], op[1], retry)
                super()._label('_st_label_1560', block=False)
                _st_label_1560 = 0
                self._timer_start()
                while (_st_label_1560 == 0):
                    _st_label_1560 += 1
                    if PatternExpr_1571.match_iter(self._ClientReceivedEvent_4, _BoundPattern1578_=('Operation_result_' + str(self._state.request_id)), SELF_ID=self._id):
                        break
                        _st_label_1560 += 1
                    elif self._timer_expired:
                        self.output('Timeout: Retrying.')
                        retry = 1
                        _st_label_1560 += 1
                    else:
                        super()._label('_st_label_1560', block=True, timeout=self._state.time_out)
                        _st_label_1560 -= 1
                else:
                    if (_st_label_1560 != 2):
                        continue
                if (_st_label_1560 != 2):
                    break
        self.output((('Local running state of client after the given set of operations: ' + str(client_running_state)) + '.'))
        super()._label('_st_label_1599', block=False)
        _st_label_1599 = 0
        while (_st_label_1599 == 0):
            _st_label_1599 += 1
            if PatternExpr_1606.match_iter(self._ClientReceivedEvent_5, SELF_ID=self._id):
                _st_label_1599 += 1
            else:
                super()._label('_st_label_1599', block=True)
                _st_label_1599 -= 1

    def update_client_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                client_running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in client_running_state):
                    return client_running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in client_running_state) and (args[1] <= len(client_running_state[args[0]]))):
                    client_running_state[args[0]] = client_running_state[args[0]][int(args[1]):]
                    return client_running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in client_running_state):
                    client_running_state[args[0]] = (client_running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def send_request(self, type, args, retry):
        if retry:
            self.send((None, 'Request', type, self._id, self._id, self._state.request_id, args), to=self._state.head)
        else:
            self._state.request_id += 1
            self.send((None, 'Request', type, self._id, self._id, self._state.request_id, args), to=self._state.head)

    def validate_result(self, result, result_proof):
        hash = self.calculate_hash(result)
        for i in result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def _Client_handler_1364(self, replicas_, head_, olympus):
        self._state.replicas = replicas_
        self._state.head = head_
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1364._labels = None
    _Client_handler_1364._notlabels = None

    def _Client_handler_1394(self, replica_public_keys_, olympus):
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' received the public keys of replicas from Olympus.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1394._labels = None
    _Client_handler_1394._notlabels = None

    def _Client_handler_1427(self, sender_id, result_shuttle):
        try:
            self._state.replica_public_keys[sender_id].verify(result_shuttle)
            result_shuttle = literal_eval(result_shuttle.message.decode('utf-8'))
        except BadSignatureError:
            self.output((('Verification of message sent by Replica ' + sender_id) + ' has failed.'))
            return
        (result, result_proof) = result_shuttle
        if self.validate_result(result, result_proof):
            self.output((((result + ' received by ') + self._state.name) + '.'))
        else:
            self.send(('Reconfiguration', self._state.name, result_shuttle), to=self._state.olympus)
    _Client_handler_1427._labels = None
    _Client_handler_1427._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        (num_replicas, request_id_counter, time_out) = (5, 0, 10)
        olympus = self.new(Olympus, args=('Olympus', num_replicas))
        self._start(olympus)
        operations = [('put', ['name', 'ankit']), ('get', ['name']), ('append', ['name', 'aggarwal']), ('get', ['name']), ('slice', ['name', 5]), ('get', ['name'])]
        client = self.new(Client, args=('Client', olympus, request_id_counter, time_out, operations))
        self._start(client)
