# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys
from client import Client

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
    _config_object = {'channel': 'Fifo', 'clock': 'Lamport'}

    def run(self):
        clients = self.new(Client, num=2)
        for c in clients:
            c.setup((clients - {c}))
        for c in clients:
            c.do()
