# -*- generated by 1.0.9 -*-
import da
PatternExpr_334 = da.pat.ConstantPattern('Shutdown')
PatternExpr_338 = da.pat.BoundPattern('_BoundPattern339_')
PatternExpr_352 = da.pat.ConstantPattern('Shutdown')
PatternExpr_356 = da.pat.FreePattern('olympus')
PatternExpr_368 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('olympus_'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_'), da.pat.FreePattern('tail_'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_418 = da.pat.TuplePattern([da.pat.ConstantPattern('Key'), da.pat.FreePattern('private_key_')])
PatternExpr_440 = da.pat.TuplePattern([da.pat.ConstantPattern('Client_keys'), da.pat.FreePattern('client_id'), da.pat.FreePattern('client_public_key')])
PatternExpr_465 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Request'), da.pat.FreePattern('type'), da.pat.FreePattern('request_from'), da.pat.FreePattern('client'), da.pat.FreePattern('request_id'), da.pat.FreePattern('client_id'), da.pat.FreePattern('args')])
PatternExpr_615 = da.pat.BoundPattern('_BoundPattern621_')
PatternExpr_766 = da.pat.BoundPattern('_BoundPattern772_')
PatternExpr_925 = da.pat.BoundPattern('_BoundPattern931_')
PatternExpr_964 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Result_shuttle'), da.pat.FreePattern('request_from'), da.pat.FreePattern('request_id'), da.pat.FreePattern('client_id'), da.pat.FreePattern('result_shuttle')])
PatternExpr_340 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern346_')]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_623 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern630_')])
PatternExpr_774 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern781_')])
PatternExpr_933 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern940_')])
PatternExpr_1548 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.FreePattern('sender')])
PatternExpr_1565 = da.pat.TuplePattern([da.pat.ConstantPattern('Get_configuration'), da.pat.FreePattern('client'), da.pat.FreePattern('client_name'), da.pat.FreePattern('client_id'), da.pat.FreePattern('client_public_key')])
PatternExpr_1608 = da.pat.TuplePattern([da.pat.ConstantPattern('Reconfiguration'), da.pat.FreePattern('sender'), da.pat.FreePattern('proof_of_misbehavior')])
PatternExpr_1663 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])
PatternExpr_1686 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1670 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.ConstantPattern(None)])])
PatternExpr_1690 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
PatternExpr_1766 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.FreePattern('replicas_'), da.pat.FreePattern('head_')])
PatternExpr_1775 = da.pat.FreePattern('olympus')
PatternExpr_1796 = da.pat.TuplePattern([da.pat.ConstantPattern('Keys'), da.pat.FreePattern('replica_public_keys_')])
PatternExpr_1803 = da.pat.FreePattern('olympus')
PatternExpr_1829 = da.pat.TuplePattern([da.pat.FreePattern('sender_id'), da.pat.ConstantPattern('Operation_result'), da.pat.FreePattern('result_shuttle')])
PatternExpr_1909 = da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1912_'), da.pat.BoundPattern('_BoundPattern1913_')])
PatternExpr_1966 = da.pat.BoundPattern('_BoundPattern1972_')
PatternExpr_2005 = da.pat.ConstantPattern('Shutdown')
PatternExpr_1916 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('Configuration'), da.pat.BoundPattern('_BoundPattern1926_'), da.pat.BoundPattern('_BoundPattern1927_')])])
PatternExpr_1974 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.BoundPattern('_BoundPattern1981_')])
PatternExpr_2009 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.ConstantPattern('Shutdown')])
_config_object = {'channel': {'reliable', 'fifo'}}
from nacl.hash import sha256
from nacl.encoding import HexEncoder
from nacl.signing import SigningKey, VerifyKey
from nacl.exceptions import BadSignatureError
from ast import literal_eval
from config import *
import read_config
import sys
import getopt
client_running_state = dict()

class Replica(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ReplicaReceivedEvent_0 = []
        self._ReplicaReceivedEvent_6 = []
        self._ReplicaReceivedEvent_7 = []
        self._ReplicaReceivedEvent_8 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_0', PatternExpr_334, sources=[PatternExpr_338], destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_1', PatternExpr_352, sources=[PatternExpr_356], destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_351]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_2', PatternExpr_368, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_367]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_3', PatternExpr_418, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_417]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_4', PatternExpr_440, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_439]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_5', PatternExpr_465, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_464]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_6', PatternExpr_615, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_7', PatternExpr_766, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_8', PatternExpr_925, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_9', PatternExpr_964, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_963])])

    def setup(self, id, name, replica_failures, replica_timeout, **rest_2458):
        super().setup(id=id, name=name, replica_failures=replica_failures, replica_timeout=replica_timeout, **rest_2458)
        self._state.id = id
        self._state.name = name
        self._state.replica_failures = replica_failures
        self._state.replica_timeout = replica_timeout
        self._state.status = 0
        self._state.running_state = dict()
        self._state.order_proof = list()
        self._state.result_proof = list()
        self._state.result_cache = dict()
        self._state.slot_number = 0
        self._state.last_slot_number = 0
        self._state.olympus = None
        self._state.replicas = None
        self._state.head = None
        self._state.tail = None
        self._state.replica_public_keys = None
        self._state.private_key = None
        self._state.client_keys = dict()
        self._state.configuration = None
        self._state.messages_received_from_client = {}
        self._state.messages_shuttle = {}
        self._state.messages_result_shuttle = {}
        self._state.messages_forwarded_request = {}

    def run(self):
        self._state.status = 1
        super()._label('_st_label_331', block=False)
        _st_label_331 = 0
        while (_st_label_331 == 0):
            _st_label_331 += 1
            if PatternExpr_340.match_iter(self._ReplicaReceivedEvent_0, _BoundPattern346_=self._state.olympus, SELF_ID=self._id):
                _st_label_331 += 1
            else:
                super()._label('_st_label_331', block=True)
                _st_label_331 -= 1

    def update_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                self._state.running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in self._state.running_state):
                    return self._state.running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in self._state.running_state) and (args[1] <= len(self._state.running_state[args[0]]))):
                    self._state.running_state[args[0]] = self._state.running_state[args[0]][int(args[1]):]
                    return self._state.running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in self._state.running_state):
                    self._state.running_state[args[0]] = (self._state.running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def validate_shuttle(self, shuttle):
        (self._state.order_proof, self._state.result_proof) = shuttle
        (self._state.slot_number, operation, self._state.configuration, order_stmt) = self._state.order_proof
        if (not (self._state.last_slot_number == (self._state.slot_number - 1))):
            return False
        for stmt in order_stmt:
            if ((not (stmt[0] == self._state.slot_number)) or (not (stmt[1] == operation)) or (not (stmt[2] == self._state.configuration))):
                return False
        hash = self._state.result_proof[0][1]
        for result_stmt in self._state.result_proof:
            if ((not (result_stmt[0] == operation)) or (not (result_stmt[1] == hash))):
                return False
        return True

    def validate_result_shuttle(self, result_shuttle):
        (result, self._state.result_proof) = result_shuttle
        hash = self.calculate_hash(result)
        for i in self._state.result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def sign_and_send(self, data, to_):
        data = ([self._state.id] + list(data))
        data[(- 1)] = self._state.private_key.sign(str(data[(- 1)]).encode('utf-8'))
        self.send(tuple(data), to=to_)

    def _Replica_handler_351(self, olympus):
        self._state.status = 2
        self.output((self._state.name + ' is immutable and shutting down.'))
    _Replica_handler_351._labels = None
    _Replica_handler_351._notlabels = None

    def _Replica_handler_367(self, olympus_, replicas_, head_, tail_, replica_public_keys_):
        self._state.olympus = olympus_
        self._state.replicas = replicas_
        self._state.head = head_
        self._state.tail = tail_
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_367._labels = None
    _Replica_handler_367._notlabels = None

    def _Replica_handler_417(self, private_key_):
        self._state.private_key = private_key_
        self.output((self._state.name + ' have received its private key from Olympus.'))
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_417._labels = None
    _Replica_handler_417._notlabels = None

    def _Replica_handler_439(self, client_id, client_public_key):
        self._state.client_keys[client_id] = VerifyKey(client_public_key, encoder=HexEncoder)
        self.send(('ACK', self._state.name), to=self._state.olympus)
    _Replica_handler_439._labels = None
    _Replica_handler_439._notlabels = None

    def _Replica_handler_464(self, sender_id, type, request_from, client, request_id, client_id, args):
        self.output((((((str(type) + ' request with request id ') + str(request_id)) + ' received by ') + self._state.name) + '.'))
        if (self._state.status == 0):
            self.output((self._state.name + ' is in PENDING state.'))
        elif (self._state.status == 1):
            self.output((self._state.name + ' is in ACTIVE state.'))
        elif (self._state.status == 2):
            self.output((self._state.name + ' is in IMMUTABLE state.'))
        if (self._state.status == 1):
            if (request_from == client):
                if (not (client_id in self._state.messages_received_from_client)):
                    self._state.messages_received_from_client[client_id] = 0
                self._state.messages_received_from_client[client_id] += 1
                try:
                    self._state.client_keys[client_id].verify(args)
                    args = literal_eval(args.message.decode('utf-8'))
                except BadSignatureError:
                    self.output((('Verification of message sent by Client ' + str(client_id)) + ' has failed.'))
                    return
                if (request_id in self._state.result_cache):
                    self.sign_and_send(('Operation_result', self._state.result_cache[request_id]), client)
                    self.output((('Result sent from cache of ' + self._state.name) + '.'))
                    return
                elif (not (self._id == self._state.head)):
                    self.sign_and_send(('Request', type, self._id, client, request_id, client_id, args), self._state.head)
                    super()._label('_st_label_612', block=False)
                    _st_label_612 = 0
                    self._timer_start()
                    while (_st_label_612 == 0):
                        _st_label_612 += 1
                        if PatternExpr_623.match_iter(self._ReplicaReceivedEvent_6, _BoundPattern630_=('Result_shuttle_' + str(request_id)), SELF_ID=self._id):
                            pass
                            _st_label_612 += 1
                        elif self._timer_expired:
                            self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
                            _st_label_612 += 1
                        else:
                            super()._label('_st_label_612', block=True, timeout=self._state.replica_timeout)
                            _st_label_612 -= 1
                    return
            else:
                try:
                    self._state.replica_public_keys[sender_id].verify(args)
                    args = literal_eval(args.message.decode('utf-8'))
                except BadSignatureError:
                    self.output((('Verification of message sent by Replica ' + str(sender_id)) + ' has failed.'))
                    return
            if (self._id == self._state.head):
                if (not (request_from == client)):
                    if (not (client_id in messages_forwared_request)):
                        messages_forwared_request[client_id] = 0
                    messages_forwared_request[client_id] += 1
                result = self.update_running_state(type, args)
                self._state.slot_number += 1
                order_stmt = [[self._state.slot_number, (type, args), self._state.configuration]]
                self._state.order_proof = [self._state.slot_number, (type, args), self._state.configuration, order_stmt]
                self._state.result_proof = [[(type, args), self.calculate_hash(result)]]
                shuttle = (self._state.order_proof, self._state.result_proof)
                self.sign_and_send(('Request', type, self._id, client, request_id, client_id, shuttle), self._state.replicas[(self._state.id + 1)])
                self._state.last_slot_number = self._state.slot_number
                super()._label('_st_label_763', block=False)
                _st_label_763 = 0
                self._timer_start()
                while (_st_label_763 == 0):
                    _st_label_763 += 1
                    if PatternExpr_774.match_iter(self._ReplicaReceivedEvent_7, _BoundPattern781_=('Result_shuttle_' + str(request_id)), SELF_ID=self._id):
                        pass
                        _st_label_763 += 1
                    elif self._timer_expired:
                        self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
                        _st_label_763 += 1
                    else:
                        super()._label('_st_label_763', block=True, timeout=self._state.replica_timeout)
                        _st_label_763 -= 1
            else:
                if (not (client_id in self._state.messages_shuttle)):
                    self._state.messages_shuttle[client_id] = 0
                self._state.messages_shuttle[client_id] += 1
                if self.validate_shuttle(args):
                    (self._state.order_proof, self._state.result_proof) = args
                    (self._state.slot_number, operation, self._state.configuration, order_stmt) = self._state.order_proof
                    self._state.last_slot_number = self._state.slot_number
                    (type, operation_args) = operation
                    result = self.update_running_state(type, operation_args)
                    self._state.order_proof[3].append([self._state.slot_number, (type, operation_args), self._state.configuration])
                    self._state.result_proof.append([(type, operation_args), self.calculate_hash(result)])
                    shuttle = (self._state.order_proof, self._state.result_proof)
                    if (self._id == self._state.tail):
                        result_shuttle = [result, self._state.result_proof]
                        self.sign_and_send(('Operation_result', result_shuttle), client)
                        self.send(('Operation_result_' + str(request_id)), to=client)
                        self.sign_and_send(('Result_shuttle', self._id, request_id, client_id, result_shuttle), self._state.tail)
                    else:
                        self.sign_and_send(('Request', type, self._id, client, request_id, client_id, shuttle), self._state.replicas[(self._state.id + 1)])
                        super()._label('_st_label_922', block=False)
                        _st_label_922 = 0
                        self._timer_start()
                        while (_st_label_922 == 0):
                            _st_label_922 += 1
                            if PatternExpr_933.match_iter(self._ReplicaReceivedEvent_8, _BoundPattern940_=('Result_shuttle_' + str(request_id)), SELF_ID=self._id):
                                pass
                                _st_label_922 += 1
                            elif self._timer_expired:
                                self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
                                _st_label_922 += 1
                            else:
                                super()._label('_st_label_922', block=True, timeout=self._state.replica_timeout)
                                _st_label_922 -= 1
                else:
                    self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
    _Replica_handler_464._labels = None
    _Replica_handler_464._notlabels = None

    def _Replica_handler_963(self, sender_id, request_from, request_id, client_id, result_shuttle):
        if (not (client_id in self._state.messages_result_shuttle)):
            self._state.messages_result_shuttle[client_id] = 0
        self._state.messages_result_shuttle[client_id] += 1
        try:
            self._state.replica_public_keys[sender_id].verify(result_shuttle)
            result_shuttle = literal_eval(result_shuttle.message.decode('utf-8'))
        except BadSignatureError:
            self.output((('Verification of message sent by Replica ' + sender_id) + ' has failed.'))
            return
        if self.validate_result_shuttle(result_shuttle):
            self._state.result_cache[request_id] = result_shuttle
            if (not (self._id == self._state.head)):
                self.sign_and_send(('Result_shuttle', self._id, request_id, client_id, result_shuttle), self._state.replicas[(self._state.id - 1)])
                self.send(('Result_shuttle_' + str(request_id)), to=self._state.replicas[(self._state.id - 1)])
            self.output((('Result shuttle is at ' + self._state.name) + '.'))
        else:
            self.output((('Result shuttle sent by Replica ' + sender_id) + ' is not valid.'))
            self.send(('Reconfiguration', self._state.name, None), to=self._state.olympus)
    _Replica_handler_963._labels = None
    _Replica_handler_963._notlabels = None

class Olympus(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._OlympusReceivedEvent_3 = []
        self._OlympusReceivedEvent_4 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_0', PatternExpr_1548, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1547]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_1', PatternExpr_1565, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1564]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_2', PatternExpr_1608, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Olympus_handler_1607]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_3', PatternExpr_1663, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_4', PatternExpr_1686, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, name, num_replicas, replica_failures, head_timeout, replica_timeout, **rest_2458):
        super().setup(name=name, num_replicas=num_replicas, replica_failures=replica_failures, head_timeout=head_timeout, replica_timeout=replica_timeout, **rest_2458)
        self._state.name = name
        self._state.num_replicas = num_replicas
        self._state.replica_failures = replica_failures
        self._state.head_timeout = head_timeout
        self._state.replica_timeout = replica_timeout
        self._state.replicas = list()
        self._state.replica_private_keys = list()
        self._state.replica_public_keys = list()
        self._state.head = None
        self._state.tail = None
        self._state.private_key = SigningKey.generate()
        self._state.public_key = self._state.private_key.verify_key.encode(encoder=HexEncoder)
        self._state.configuration = None
        for i in range(self._state.num_replicas):
            if (i == 0):
                replica = self.new(Replica, args=(i, 'Head', self._state.replica_failures, self._state.head_timeout))
                self._state.head = replica
            elif (i == (self._state.num_replicas - 1)):
                replica = self.new(Replica, args=(i, 'Tail', self._state.replica_failures, self._state.replica_timeout))
                self._state.tail = replica
            else:
                replica = self.new(Replica, args=(i, ('Replica ' + str(i)), self._state.replica_failures, self._state.replica_timeout))
            self._state.replicas.append(replica)
            signing_key = SigningKey.generate()
            verify_key = signing_key.verify_key.encode(encoder=HexEncoder)
            self._state.replica_private_keys.append(signing_key)
            self._state.replica_public_keys.append(verify_key)

    def run(self):
        self._start(self._state.replicas)
        self.send(('Configuration', self._id, self._state.replicas, self._state.head, self._state.tail, self._state.replica_public_keys), to=self._state.replicas)
        for i in range(len(self._state.replicas)):
            self.send(('Key', self._state.replica_private_keys[i]), to=self._state.replicas[i])
        super()._label('_st_label_1660', block=False)
        _st_label_1660 = 0
        while (_st_label_1660 == 0):
            _st_label_1660 += 1
            if PatternExpr_1670.match_iter(self._OlympusReceivedEvent_3, SELF_ID=self._id):
                _st_label_1660 += 1
            else:
                super()._label('_st_label_1660', block=True)
                _st_label_1660 -= 1
        super()._label('_st_label_1683', block=False)
        _st_label_1683 = 0
        while (_st_label_1683 == 0):
            _st_label_1683 += 1
            if PatternExpr_1690.match_iter(self._OlympusReceivedEvent_4, SELF_ID=self._id):
                _st_label_1683 += 1
            else:
                super()._label('_st_label_1683', block=True)
                _st_label_1683 -= 1

    def _Olympus_handler_1547(self, sender):
        self.output((('ACK from ' + str(sender)) + '.'))
    _Olympus_handler_1547._labels = None
    _Olympus_handler_1547._notlabels = None

    def _Olympus_handler_1564(self, client, client_name, client_id, client_public_key):
        self.send(('Configuration', self._state.replicas, self._state.head), to=client)
        self.send(('Keys', self._state.replica_public_keys), to=client)
        self.send(('Client_keys', client_id, client_public_key), to=self._state.replicas)
        self.output((('Configuration sent to ' + str(client_name)) + '.'))
    _Olympus_handler_1564._labels = None
    _Olympus_handler_1564._notlabels = None

    def _Olympus_handler_1607(self, sender, proof_of_misbehavior):
        self.output((('Reconfiguration request received from ' + str(sender)) + '.'))
        self.output('No reconfiguration mechanism implemented yet.')
    _Olympus_handler_1607._labels = None
    _Olympus_handler_1607._notlabels = None

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._ClientReceivedEvent_3 = []
        self._ClientReceivedEvent_4 = []
        self._ClientReceivedEvent_5 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_1766, sources=[PatternExpr_1775], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1765]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_1', PatternExpr_1796, sources=[PatternExpr_1803], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1795]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_2', PatternExpr_1829, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_1828]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_3', PatternExpr_1909, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_4', PatternExpr_1966, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_5', PatternExpr_2005, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, client_id, olympus, request_id, client_timeout, operations, **rest_2458):
        super().setup(client_id=client_id, olympus=olympus, request_id=request_id, client_timeout=client_timeout, operations=operations, **rest_2458)
        self._state.client_id = client_id
        self._state.olympus = olympus
        self._state.request_id = request_id
        self._state.client_timeout = client_timeout
        self._state.operations = operations
        self._state.name = ('Client ' + str(self._state.client_id))
        self._state.replicas = None
        self._state.head = None
        self._state.replica_public_keys = None
        self._state.private_key = SigningKey.generate()
        self._state.public_key = self._state.private_key.verify_key.encode(encoder=HexEncoder)

    def run(self):
        if (self._state.replicas is None):
            self.send(('Get_configuration', self._id, self._state.name, self._state.client_id, self._state.public_key), to=self._state.olympus)
            super()._label('_st_label_1906', block=False)
            _st_label_1906 = 0
            while (_st_label_1906 == 0):
                _st_label_1906 += 1
                if PatternExpr_1916.match_iter(self._ClientReceivedEvent_3, _BoundPattern1926_=self._state.replicas, _BoundPattern1927_=self._state.head, SELF_ID=self._id):
                    _st_label_1906 += 1
                else:
                    super()._label('_st_label_1906', block=True)
                    _st_label_1906 -= 1
        for op in self._state.operations:
            self.output((('Local client state is updated with response ' + self.update_client_running_state(op[0], op[1])) + '.'))
            retry = 0
            while True:
                self.send_request(op[0], op[1], retry)
                super()._label('_st_label_1963', block=False)
                _st_label_1963 = 0
                self._timer_start()
                while (_st_label_1963 == 0):
                    _st_label_1963 += 1
                    if PatternExpr_1974.match_iter(self._ClientReceivedEvent_4, _BoundPattern1981_=('Operation_result_' + str(self._state.request_id)), SELF_ID=self._id):
                        break
                        _st_label_1963 += 1
                    elif self._timer_expired:
                        self.output('Timeout: Retrying.')
                        retry = 1
                        _st_label_1963 += 1
                    else:
                        super()._label('_st_label_1963', block=True, timeout=self._state.client_timeout)
                        _st_label_1963 -= 1
                else:
                    if (_st_label_1963 != 2):
                        continue
                if (_st_label_1963 != 2):
                    break
        self.output((('Local running state of client after the given set of operations: ' + str(client_running_state)) + '.'))
        super()._label('_st_label_2002', block=False)
        _st_label_2002 = 0
        while (_st_label_2002 == 0):
            _st_label_2002 += 1
            if PatternExpr_2009.match_iter(self._ClientReceivedEvent_5, SELF_ID=self._id):
                _st_label_2002 += 1
            else:
                super()._label('_st_label_2002', block=True)
                _st_label_2002 -= 1

    def update_client_running_state(self, type, args):
        if (type == 'put'):
            if (len(args) > 1):
                client_running_state[args[0]] = args[1]
            return 'OK'
        elif (type == 'get'):
            if (len(args) > 0):
                if (args[0] in client_running_state):
                    return client_running_state[args[0]]
                else:
                    return ''
        elif (type == 'slice'):
            if (len(args) > 1):
                if ((args[0] in client_running_state) and (args[1] <= len(client_running_state[args[0]]))):
                    client_running_state[args[0]] = client_running_state[args[0]][int(args[1]):]
                    return client_running_state[args[0]]
                else:
                    return 'fail'
        elif (type == 'append'):
            if (len(args) > 1):
                if (args[0] in client_running_state):
                    client_running_state[args[0]] = (client_running_state[args[0]] + args[1])
                    return 'OK'
                else:
                    return 'fail'

    def send_request(self, type, args, retry):
        args = self._state.private_key.sign(str(args).encode('utf-8'))
        if retry:
            self.send((None, 'Request', type, self._id, self._id, self._state.request_id, self._state.client_id, args), to=self._state.head)
        else:
            self._state.request_id += 1
            self.send((None, 'Request', type, self._id, self._id, self._state.request_id, self._state.client_id, args), to=self._state.head)

    def validate_result(self, result, result_proof):
        hash = self.calculate_hash(result)
        for i in result_proof:
            if (not (hash == i[1])):
                return False
        return True

    def calculate_hash(self, val):
        if isinstance(val, str):
            return sha256(str.encode(val), encoder=HexEncoder)
        return sha256(val, encoder=HexEncoder)

    def _Client_handler_1765(self, replicas_, head_, olympus):
        self._state.replicas = replicas_
        self._state.head = head_
        self.output((self._state.name + ' is configured.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1765._labels = None
    _Client_handler_1765._notlabels = None

    def _Client_handler_1795(self, replica_public_keys_, olympus):
        self._state.replica_public_keys = [VerifyKey(key, encoder=HexEncoder) for key in replica_public_keys_]
        self.output((self._state.name + ' received the public keys of replicas from Olympus.'))
        self.send(('ACK', self._state.name), to=olympus)
    _Client_handler_1795._labels = None
    _Client_handler_1795._notlabels = None

    def _Client_handler_1828(self, sender_id, result_shuttle):
        try:
            self._state.replica_public_keys[sender_id].verify(result_shuttle)
            result_shuttle = literal_eval(result_shuttle.message.decode('utf-8'))
        except BadSignatureError:
            self.output((('Verification of message sent by Replica ' + sender_id) + ' has failed.'))
            return
        (result, result_proof) = result_shuttle
        if self.validate_result(result, result_proof):
            self.output((((result + ' received by ') + self._state.name) + '.'))
        else:
            self.send(('Reconfiguration', self._state.name, result_shuttle), to=self._state.olympus)
    _Client_handler_1828._labels = None
    _Client_handler_1828._notlabels = None

def parse_program_args(argv):
    inputfile = ''
    outputfile = ''
    try:
        (opts, args) = getopt.getopt(argv, 'hi:o:', ['ifile=', 'ofile='])
    except getopt.GetoptError:
        self.output('Error in parsing arguments')
        return None
    for (opt, arg) in opts:
        if (opt in ('-i', '--ifile')):
            inputfile = arg
        elif (opt in ('-o', '--ofile')):
            outputfile = arg
    return [inputfile, outputfile]

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        if (len(sys.argv) < 2):
            self.output('Incorrect argument count. Must specify the input configuration file atleast')
            return
        [infile, outfile] = parse_program_args(sys.argv[1:])
        if (infile == None):
            self.output('Must specify input configuration file!')
            sys.exit(2)
        config_dict = read_config.parse_config_file(infile)
        global_config = GlobalConfig(config_dict)
        client_config = ClientConfig(config_dict)
        replica_config = ReplicaConfig(config_dict)
        self.output(('Running BCR simulation for test case: ' + global_config.test_case_name))
        request_id_counter = 0
        olympus = self.new(Olympus, args=('Olympus', replica_config.num_replica, replica_config.failures, replica_config.head_timeout, replica_config.nonhead_timeout))
        self._start(olympus)
        clients = list()
        for i in range(client_config.num_client):
            modified_ops = list(map((lambda o: (o.type.name, o.args_list)), client_config.workloads[i]))
            self.output(('Ops are: ' + str(modified_ops)))
            client = self.new(Client, args=(i, olympus, request_id_counter, client_config.client_timeout, modified_ops))
            clients.append(client)
        self._start(clients)
